# Simple Databricks App Configuration
# Financial Analyst Agent with Smart Routing

command:
  - "sh"
  - "-c"
  - "pip install --upgrade pip && pip install -q websockets==13.1 && pip install -q yfinance pandas gradio requests && python simple_app.py"

env:
  - name: GRADIO_SERVER_NAME
    value: "0.0.0.0"
  - name: GRADIO_SERVER_PORT
    value: "8080"
