# Simple Databricks App Configuration
# Financial Analyst Agent with Smart Routing

command:
  - "sh"
  - "-c"
  - "pip cache purge && pip install --no-cache-dir --force-reinstall yfinance==0.2.28 pandas gradio requests && python simple_app.py"

env:
  - name: GRADIO_SERVER_NAME
    value: "0.0.0.0"
  - name: GRADIO_SERVER_PORT
    value: "8080"
