# Simple Databricks App Configuration
# Financial Analyst Agent with Smart Routing

command:
  - "sh"
  - "-c"
  - "pip install --no-cache-dir yfinance==0.1.96 pandas gradio requests && python simple_app.py"

env:
  - name: GRADIO_SERVER_NAME
    value: "0.0.0.0"
  - name: GRADIO_SERVER_PORT
    value: "8080"
